version: 0.2

phases:
  install:
    commands:
      - npm i -g yarn
      - yarn
  build:
    commands:
      - yarn lint
      - yarn test
      - chmod +x scripts/deploy.sh
      - scripts/deploy.sh $STAGE

#cache:
#  paths:
#    - 'node_modules/**/*'
